language: cpp
      
before_install:
  - cat /proc/cpuinfo
  - cat /etc/lsb-release
  - sudo apt-get update -qq
  - sudo apt-get install autopoint libtool intltool gperf p7zip-full wine
  
before_script:
  - git clone https://github.com/mxe/mxe
  - cd mxe && make wxwidgets libsndfile ogg vorbis expat cmake
  - export PATH=~/mxe/usr/bin:$PATH
  - i686-w64-mingw32.static-g++ -v

script:
  - i686-w64-mingw32.static-g++ -v -o test test.cpp && wine ./test.exe
