language: cpp

before_install:
  # travis is too slow to compile mxe
  # use precompiled mxe from http://pkg.mxe.cc
  - sudo sh -c 'echo "deb http://pkg.mxe.cc/repos/apt/debian wheezy main" > /etc/apt/sources.list.d/mxeapt.list'
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys D43A795B73B16ABE9643FE1AFD8FFF16DB45C6AB
  - sudo apt-get update -qq
  - sudo apt-get install -y mxe-i686-w64-mingw32.static-gcc xvfb wine
  
before_script:
  - export PATH=/usr/lib/mxe/usr/bin:$PATH
  - i686-w64-mingw32.static-g++ -v
  # disable wine-gecko installer prompt
  - export WINEDLLOVERRIDES="mscoree,mshtml="
  # need X server to get around wine stuff
  - sudo Xvfb :3 &
  - export DISPLAY=:3

script:
  - i686-w64-mingw32.static-g++ -mconsole -o test.exe test.cpp && wine ./test.exe
