language: cpp
      
before_install:
  - echo XXXXXX Before Install XXXXXX
  - cat /proc/cpuinfo
  - sudo apt-get update -qq
  - sudo apt-get install autopoint libtoolize gperf 7za wine
  
before_script:
  - echo XXXXXX After Script XXXXX
  - git clone https://github.com/mxe/mxe
  - cd mxe && make wxwidgets libsndfile ogg vorbis expat cmake
  - export PATH=~/mxe/usr/bin:$PATH
  - i686-w64-mingw32.static-g++ -v

script:
  - i686-w64-mingw32.static-g++ -v -o test test.cpp && wine ./test.exe
