language: cpp

before_install:
  - cat /proc/cpuinfo
  - cat /etc/lsb-release
  - sudo sh -c 'echo "deb http://pkg.mxe.cc/repos/apt/debian wheezy main" > /etc/apt/sources.list.d/mxeapt.list'
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys D43A795B73B16ABE9643FE1AFD8FFF16DB45C6AB
  - sudo apt-get update -qq
  - sudo apt-get install -y mxe-i686-w64-mingw32.static-gcc wine
  
before_script:
  - export PATH=/usr/lib/mxe/usr/bin:$PATH
  - i686-w64-mingw32.static-g++ -v

script:
  - i686-w64-mingw32.static-g++ -v -o test test.cpp && wine ./test.exe
