language: cpp

apt:
  sources:
      - ubuntu-toolchain-r-test
  packages:
      - autopoint
      - libtoolize
      - gperf
      - 7za
      - wine
      
before_install:
  - git clone https://github.com/mxe/mxe
  - cd mxe && make wxwidgets libsndfile ogg vorbis expat cmake
  - export PATH=~/mxe/usr/bin:$PATH
  - i686-w64-mingw32.static-g++ -v
script:
  - i686-w64-mingw32.static-g++ -v -o test test.cpp && wine ./test.exe
